# Generated by Django 2.2.2 on 2019-07-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='decorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorname', models.CharField(help_text='enter decor name', max_length=255, unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='decor')),
            ],
            options={
                'verbose_name': 'decor',
                'verbose_name_plural': 'decors',
                'db_table': 'decor',
                'ordering': ('decorname',),
            },
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('southindian', 'southindian'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('bakery', 'bakery'), ('none', 'none'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('southindian', 'southindian'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('bakery', 'bakery'), ('none', 'none'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('southindian', 'southindian'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('bakery', 'bakery'), ('none', 'none'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('southindian', 'southindian'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('bakery', 'bakery'), ('none', 'none'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('select', '--select--'), ('No', 'no'), ('Yes', 'yes')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('select_type', '--selecttype--'), ('non-veg', 'non-veg'), ('veg', 'veg'), ('both', 'both')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
