# Generated by Django 2.2.2 on 2019-07-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190716_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='venueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venuename', models.CharField(help_text='enter venue name', max_length=255, unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='venue')),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
                'db_table': 'venue',
                'ordering': ('venuename',),
            },
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('italian', 'italian'), ('chinese', 'chinese'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('none', 'none'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('italian', 'italian'), ('chinese', 'chinese'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('none', 'none'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('italian', 'italian'), ('chinese', 'chinese'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('none', 'none'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('italian', 'italian'), ('chinese', 'chinese'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('none', 'none'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('No', 'no'), ('Yes', 'yes'), ('select', '--select--')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('both', 'both'), ('non-veg', 'non-veg'), ('veg', 'veg'), ('select_type', '--selecttype--')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
