# Generated by Django 2.2.2 on 2019-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190716_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='partyreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(help_text='user name', max_length=255)),
                ('pemail', models.CharField(help_text='users email', max_length=255)),
                ('phone', models.CharField(help_text='enter phone no', max_length=255)),
                ('pdate', models.DateField(help_text='events date')),
                ('pguest', models.CharField(help_text='no of guest', max_length=255)),
                ('venuename', models.CharField(help_text='your venue', max_length=255)),
                ('decorname', models.CharField(help_text='your decor', max_length=255)),
                ('photo', models.CharField(help_text='photographer', max_length=255)),
                ('ds', models.CharField(help_text='dj & sound', max_length=255)),
            ],
            options={
                'verbose_name': 'party',
                'verbose_name_plural': 'parties',
                'db_table': 'party',
                'ordering': ('pname',),
            },
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('none', 'none'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('southindian', 'southindian'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('chinese', 'chinese')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('none', 'none'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('southindian', 'southindian'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('chinese', 'chinese')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('none', 'none'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('southindian', 'southindian'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('chinese', 'chinese')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('none', 'none'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('southindian', 'southindian'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('chinese', 'chinese')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('select', '--select--')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('select_type', '--selecttype--'), ('non-veg', 'non-veg'), ('veg', 'veg'), ('both', 'both')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
