# Generated by Django 2.2.2 on 2019-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190716_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('none', 'none'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('none', 'none'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('none', 'none'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('none', 'none'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('select', '--select--'), ('yes', 'yes'), ('no', 'no')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('both', 'both'), ('non-veg', 'non-veg'), ('veg', 'veg'), ('select_type', '--selecttype--')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
