# Generated by Django 2.2.2 on 2019-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190716_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='venue'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('none', 'none'), ('chinese', 'chinese'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('none', 'none'), ('chinese', 'chinese'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('none', 'none'), ('southindian', 'southindian'), ('chinese', 'chinese')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('northindian', 'northindian'), ('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('italian', 'italian'), ('none', 'none'), ('chinese', 'chinese'), ('southindian', 'southindian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('both', 'both'), ('non-veg', 'non-veg'), ('select_type', '--selecttype--'), ('veg', 'veg')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
