# Generated by Django 2.2.2 on 2019-07-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190716_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('jaipur', 'JAIPUR'), ('mumbai', 'mumbai'), ('udaipur', 'udaipar'), ('jodhpur', 'jodhpur'), ('chennai', 'chennai'), ('banglore', 'banglore'), ('select_city', '--selectcity--'), ('nagpur', 'nagpur'), ('delhi', 'delhi')], default='select_city', help_text='enter city', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('no', 'no'), ('select', '--select--'), ('yes', 'yes')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('select_type', '--selecttype--'), ('veg', 'veg'), ('non-veg', 'non-veg'), ('both', 'both')], default='select_type', help_text='enter cusine', max_length=255),
        ),
    ]
