# Generated by Django 2.2.2 on 2019-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190716_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallerym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery')),
                ('group', models.CharField(help_text='name of group', max_length=255)),
                ('work', models.CharField(help_text='work shown in image', max_length=255)),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'db_table': 'gallery',
                'ordering': ('work',),
            },
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('none', 'none')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('none', 'none')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('none', 'none')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('bakery', 'bakery'), ('select_cusine', '--selectCusine--'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('none', 'none')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes'), ('select', '--select--')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('select_type', '--selecttype--'), ('both', 'both'), ('veg', 'veg'), ('non-veg', 'non-veg')], default='select_type', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('Banglore', 'banglore'), ('Delhi', 'delhi'), ('Udaipur', 'udaipar'), ('Jodhpur', 'jodhpur'), ('Chennai', 'chennai'), ('select_city', '--selectcity--'), ('Mumbai', 'mumbai'), ('Jaipur', 'JAIPUR'), ('Nagpur', 'nagpur')], default='select_city', help_text='enter city', max_length=255),
        ),
    ]
