# Generated by Django 2.2.2 on 2019-07-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190717_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyreg',
            name='ptype',
            field=models.CharField(default=0, help_text='pd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('italian', 'italian'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('none', 'none'), ('bakery', 'bakery'), ('chinese', 'chinese'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('italian', 'italian'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('none', 'none'), ('bakery', 'bakery'), ('chinese', 'chinese'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('italian', 'italian'), ('northindian', 'northindian'), ('southindian', 'southindian'), ('none', 'none'), ('bakery', 'bakery'), ('chinese', 'chinese'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('fastfood', 'fastfood'), ('italian', 'italian'), ('southindian', 'southindian'), ('northindian', 'northindian'), ('none', 'none'), ('bakery', 'bakery'), ('chinese', 'chinese'), ('select_cusine', '--selectCusine--')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('Delhi', 'delhi'), ('Udaipur', 'udaipar'), ('Chennai', 'chennai'), ('Mumbai', 'mumbai'), ('Jaipur', 'JAIPUR'), ('Banglore', 'banglore'), ('Nagpur', 'nagpur'), ('select_city', '--selectcity--'), ('Jodhpur', 'jodhpur')], default='select_city', help_text='enter city', max_length=255),
        ),
    ]
