# Generated by Django 2.2.2 on 2019-07-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190717_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('southindian', 'southindian'), ('none', 'none'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('southindian', 'southindian'), ('none', 'none'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('southindian', 'southindian'), ('none', 'none'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('southindian', 'southindian'), ('none', 'none'), ('chinese', 'chinese'), ('northindian', 'northindian'), ('select_cusine', '--selectCusine--'), ('fastfood', 'fastfood'), ('italian', 'italian'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('select_type', '--selecttype--'), ('both', 'both'), ('non-veg', 'non-veg'), ('veg', 'veg')], default='select_type', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('Delhi', 'delhi'), ('Jodhpur', 'jodhpur'), ('Chennai', 'chennai'), ('Banglore', 'banglore'), ('Udaipur', 'udaipar'), ('Nagpur', 'nagpur'), ('Jaipur', 'JAIPUR'), ('Mumbai', 'mumbai'), ('select_city', '--selectcity--')], default='select_city', help_text='enter city', max_length=255),
        ),
    ]
