# Generated by Django 2.2.2 on 2019-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190717_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('northindian', 'northindian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('none', 'none'), ('chinese', 'chinese'), ('italian', 'italian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('northindian', 'northindian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('none', 'none'), ('chinese', 'chinese'), ('italian', 'italian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('northindian', 'northindian'), ('chinese', 'chinese'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('none', 'none'), ('italian', 'italian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('northindian', 'northindian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('bakery', 'bakery'), ('fastfood', 'fastfood'), ('none', 'none'), ('chinese', 'chinese'), ('italian', 'italian')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='drinks',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('select', '--select--')], default='select1', help_text='enter yes or no', max_length=255),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('Jaipur', 'JAIPUR'), ('Udaipur', 'udaipar'), ('Chennai', 'chennai'), ('Jodhpur', 'jodhpur'), ('Banglore', 'banglore'), ('Mumbai', 'mumbai'), ('Nagpur', 'nagpur'), ('select_city', '--selectcity--'), ('Delhi', 'delhi')], default='select_city', help_text='enter city', max_length=255),
        ),
    ]
