# Generated by Django 2.2.2 on 2019-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190926_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='cusine1',
            field=models.CharField(choices=[('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine2',
            field=models.CharField(choices=[('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine3',
            field=models.CharField(choices=[('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cusine4',
            field=models.CharField(choices=[('chinese', 'chinese'), ('northindian', 'northindian'), ('italian', 'italian'), ('southindian', 'southindian'), ('select_cusine', '--selectCusine--'), ('none', 'none'), ('fastfood', 'fastfood'), ('bakery', 'bakery')], default='select_cusine', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='typef',
            field=models.CharField(choices=[('non-veg', 'non-veg'), ('veg', 'veg'), ('select_type', '--selecttype--'), ('both', 'both')], default='select_type', help_text='enter cusine', max_length=255),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'mumbai'), ('Udaipur', 'udaipar'), ('select_city', '--selectcity--'), ('Jaipur', 'JAIPUR'), ('Chennai', 'chennai'), ('Banglore', 'banglore'), ('Nagpur', 'nagpur'), ('Delhi', 'delhi'), ('Jodhpur', 'jodhpur')], default='select_city', help_text='enter city', max_length=255),
        ),
    ]
